#ifndef MEMORY_LAYOUT_H
#define MEMORY_LAYOUT_H

#include <stdint.h>

#define PAGE_SIZE_BYTES            4096U
#define KERNEL_VIRTUAL_BASE        0xC0000000U
#define KERNEL_EARLY_MAP_BYTES     (32U * 1024U * 1024U)
#define KERNEL_IDENTITY_MAP_BYTES  KERNEL_EARLY_MAP_BYTES
#define KERNEL_HEAP_START          0xC0800000U
#define KERNEL_HEAP_SIZE_BYTES     (4U * 1024U * 1024U)
#define KERNEL_FRAMEBUFFER_WINDOW_BASE      0xC2000000U
#define KERNEL_FRAMEBUFFER_WINDOW_SIZE_BYTES (16U * 1024U * 1024U)
#define PMM_BITMAP_PHYS_BASE       0x01000000U

#define USER_DEMO_CODE_BASE        0x01400000U
#define USER_DEMO_CODE_SIZE_BYTES  PAGE_SIZE_BYTES
#define USER_DEMO_STACK_BASE       0x01401000U
#define USER_DEMO_STACK_SIZE_BYTES PAGE_SIZE_BYTES
#define USER_DEMO_STACK_TOP        (USER_DEMO_STACK_BASE + USER_DEMO_STACK_SIZE_BYTES)
#define USER_DEMO_REGION_BASE      USER_DEMO_CODE_BASE
#define USER_DEMO_REGION_END       (USER_DEMO_STACK_BASE + USER_DEMO_STACK_SIZE_BYTES)

#define USER_FAULT_STACK_BASE       0x01402000U
#define USER_FAULT_STACK_SIZE_BYTES PAGE_SIZE_BYTES
#define USER_FAULT_STACK_TOP        (USER_FAULT_STACK_BASE + USER_FAULT_STACK_SIZE_BYTES)
/* Intentionally unmapped address used to verify user fault handling. */
#define USER_FAULT_BAD_EIP          (KERNEL_EARLY_MAP_BYTES + PAGE_SIZE_BYTES)

#define USER_ELF_SLOT0_IMAGE_BASE        0x01410000U
#define USER_ELF_SLOT0_IMAGE_SIZE_BYTES  (64U * 1024U)
#define USER_ELF_SLOT0_STACK_BASE        0x01420000U
#define USER_ELF_SLOT0_STACK_SIZE_BYTES  PAGE_SIZE_BYTES
#define USER_ELF_SLOT0_STACK_TOP         (USER_ELF_SLOT0_STACK_BASE + USER_ELF_SLOT0_STACK_SIZE_BYTES)
#define USER_ELF_SLOT0_REGION_BASE       USER_ELF_SLOT0_IMAGE_BASE
#define USER_ELF_SLOT0_REGION_END        (USER_ELF_SLOT0_STACK_BASE + USER_ELF_SLOT0_STACK_SIZE_BYTES)

#define USER_ELF_SLOT1_IMAGE_BASE        0x01422000U
#define USER_ELF_SLOT1_IMAGE_SIZE_BYTES  (64U * 1024U)
#define USER_ELF_SLOT1_STACK_BASE        0x01432000U
#define USER_ELF_SLOT1_STACK_SIZE_BYTES  PAGE_SIZE_BYTES
#define USER_ELF_SLOT1_STACK_TOP         (USER_ELF_SLOT1_STACK_BASE + USER_ELF_SLOT1_STACK_SIZE_BYTES)
#define USER_ELF_SLOT1_REGION_BASE       USER_ELF_SLOT1_IMAGE_BASE
#define USER_ELF_SLOT1_REGION_END        (USER_ELF_SLOT1_STACK_BASE + USER_ELF_SLOT1_STACK_SIZE_BYTES)

#define USER_ELF_SLOT2_IMAGE_BASE        0x01434000U
#define USER_ELF_SLOT2_IMAGE_SIZE_BYTES  (64U * 1024U)
#define USER_ELF_SLOT2_STACK_BASE        0x01444000U
#define USER_ELF_SLOT2_STACK_SIZE_BYTES  PAGE_SIZE_BYTES
#define USER_ELF_SLOT2_STACK_TOP         (USER_ELF_SLOT2_STACK_BASE + USER_ELF_SLOT2_STACK_SIZE_BYTES)
#define USER_ELF_SLOT2_REGION_BASE       USER_ELF_SLOT2_IMAGE_BASE
#define USER_ELF_SLOT2_REGION_END        (USER_ELF_SLOT2_STACK_BASE + USER_ELF_SLOT2_STACK_SIZE_BYTES)

#define USER_ELF_SLOT3_IMAGE_BASE        0x01445000U
#define USER_ELF_SLOT3_IMAGE_SIZE_BYTES  (64U * 1024U)
#define USER_ELF_SLOT3_STACK_BASE        0x01455000U
#define USER_ELF_SLOT3_STACK_SIZE_BYTES  PAGE_SIZE_BYTES
#define USER_ELF_SLOT3_STACK_TOP         (USER_ELF_SLOT3_STACK_BASE + USER_ELF_SLOT3_STACK_SIZE_BYTES)
#define USER_ELF_SLOT3_REGION_BASE       USER_ELF_SLOT3_IMAGE_BASE
#define USER_ELF_SLOT3_REGION_END        (USER_ELF_SLOT3_STACK_BASE + USER_ELF_SLOT3_STACK_SIZE_BYTES)

#define USER_ELF_SLOT4_IMAGE_BASE        0x01456000U
#define USER_ELF_SLOT4_IMAGE_SIZE_BYTES  (64U * 1024U)
#define USER_ELF_SLOT4_STACK_BASE        0x01466000U
#define USER_ELF_SLOT4_STACK_SIZE_BYTES  PAGE_SIZE_BYTES
#define USER_ELF_SLOT4_STACK_TOP         (USER_ELF_SLOT4_STACK_BASE + USER_ELF_SLOT4_STACK_SIZE_BYTES)
#define USER_ELF_SLOT4_REGION_BASE       USER_ELF_SLOT4_IMAGE_BASE
#define USER_ELF_SLOT4_REGION_END        (USER_ELF_SLOT4_STACK_BASE + USER_ELF_SLOT4_STACK_SIZE_BYTES)

#define USER_ELF_SLOT5_IMAGE_BASE        0x01467000U
#define USER_ELF_SLOT5_IMAGE_SIZE_BYTES  (64U * 1024U)
#define USER_ELF_SLOT5_STACK_BASE        0x01477000U
#define USER_ELF_SLOT5_STACK_SIZE_BYTES  PAGE_SIZE_BYTES
#define USER_ELF_SLOT5_STACK_TOP         (USER_ELF_SLOT5_STACK_BASE + USER_ELF_SLOT5_STACK_SIZE_BYTES)
#define USER_ELF_SLOT5_REGION_BASE       USER_ELF_SLOT5_IMAGE_BASE
#define USER_ELF_SLOT5_REGION_END        (USER_ELF_SLOT5_STACK_BASE + USER_ELF_SLOT5_STACK_SIZE_BYTES)

#define USER_ELF_SLOT6_IMAGE_BASE        0x01478000U
#define USER_ELF_SLOT6_IMAGE_SIZE_BYTES  (64U * 1024U)

#endif /* MEMORY_LAYOUT_H */
